In [26]:
import requests
import pandas as pd
# from pandas import json_normalize
import json 

response = requests.get("https://api.data.gov.in/resource/d36ca31d-00b5-4bbc-8cfd-684cb208a038?api-key=579b464db66ec23bdd000001cdd3946e44ce4aad7209ff7b23ac571b&format=json&offset=0&limit=10")

In [35]:
data_json = response.json()
data = json.dumps(data_json)
data

'{"index_name": "d36ca31d-00b5-4bbc-8cfd-684cb208a038", "title": "Variety-wise Daily Market Prices of Sabu Dan 2020", "desc": "Variety-wise Daily Market Prices of Sabu Dan 2020", "org_type": "Central", "org": ["Ministry of Agriculture and Farmers Welfare", "Department of Agriculture and Farmers Welfare", "Directorate of Marketing and Inspection (DMI)"], "sector": ["Agriculture", "Agricultural Marketing"], "source": "data.gov.in", "catalog_uuid": "ad1a6c97-7968-4190-bc2c-572b7db18b6d", "visualizable": "1", "active": "1", "created": 1639533445, "updated": 1639540258, "created_date": "2021-12-15T02:57:25Z", "updated_date": "2021-12-15T09:20:58Z", "external_ws": 0, "external_ws_url": "", "target_bucket": {"index": "agmarknet", "type": "ad1a6c97-7968-4190-bc2c-572b7db18b6d", "field": "d36ca31d-00b5-4bbc-8cfd-684cb208a038"}, "field": [{"id": "state", "name": "state", "type": "keyword"}, {"id": "district", "name": "district", "type": "keyword"}, {"id": "market", "name": "market", "type": "keyword"}, {"id": "commodity", "name": "commodity", "type": "keyword"}, {"id": "variety", "name": "variety", "type": "keyword"}, {"id": "arrival_date", "name": "arrival_date", "type": "date"}, {"id": "min_price", "name": "min_price", "type": "double"}, {"id": "max_price", "name": "max_price", "type": "double"}, {"id": "modal_price", "name": "modal_price", "type": "double"}], "message": "Resource lists", "version": "2.2.0", "status": "ok", "total": 38, "count": 10, "limit": "10", "offset": "0", "records": [{"state": "Maharashtra", "district": "Mumbai", "market": "Mumbai", "commodity": "Sabu Dan", "variety": "Other", "arrival_date": "2020-01-01T02:57:25Z", "min_price": 5600, "max_price": 6000, "modal_price": 5800}, {"state": "Maharashtra", "district": "Mumbai", "market": "Mumbai", "commodity": "Sabu Dan", "variety": "Other", "arrival_date": "2020-01-03T02:57:25Z", "min_price": 5600, "max_price": 6000, "modal_price": 5800}, {"state": "Maharashtra", "district": "Mumbai", "market": "Mumbai", "commodity": "Sabu Dan", "variety": "Other", "arrival_date": "2020-01-04T02:57:25Z", "min_price": 5600, "max_price": 6000, "modal_price": 5800}, {"state": "Maharashtra", "district": "Mumbai", "market": "Mumbai", "commodity": "Sabu Dan", "variety": "Other", "arrival_date": "2020-01-06T02:57:25Z", "min_price": 5600, "max_price": 6000, "modal_price": 5800}, {"state": "Maharashtra", "district": "Mumbai", "market": "Mumbai", "commodity": "Sabu Dan", "variety": "Other", "arrival_date": "2020-01-07T02:57:25Z", "min_price": 5600, "max_price": 6000, "modal_price": 5800}, {"state": "Maharashtra", "district": "Mumbai", "market": "Mumbai", "commodity": "Sabu Dan", "variety": "Other", "arrival_date": "2020-01-08T02:57:25Z", "min_price": 5600, "max_price": 6000, "modal_price": 5800}, {"state": "Maharashtra", "district": "Mumbai", "market": "Mumbai", "commodity": "Sabu Dan", "variety": "Other", "arrival_date": "2020-01-09T02:57:25Z", "min_price": 5500, "max_price": 5800, "modal_price": 5600}, {"state": "Maharashtra", "district": "Mumbai", "market": "Mumbai", "commodity": "Sabu Dan", "variety": "Other", "arrival_date": "2020-01-10T02:57:25Z", "min_price": 5500, "max_price": 5800, "modal_price": 5600}, {"state": "Maharashtra", "district": "Mumbai", "market": "Mumbai", "commodity": "Sabu Dan", "variety": "Other", "arrival_date": "2020-01-11T02:57:25Z", "min_price": 5500, "max_price": 5800, "modal_price": 5600}, {"state": "Maharashtra", "district": "Mumbai", "market": "Mumbai", "commodity": "Sabu Dan", "variety": "Other", "arrival_date": "2020-01-13T02:57:25Z", "min_price": 5500, "max_price": 5800, "modal_price": 5600}]}'

In [36]:
data_extract = json.loads(data)
data_gen_info = data_extract["field"]
data_gen_info

[{'id': 'state', 'name': 'state', 'type': 'keyword'},
 {'id': 'district', 'name': 'district', 'type': 'keyword'},
 {'id': 'market', 'name': 'market', 'type': 'keyword'},
 {'id': 'commodity', 'name': 'commodity', 'type': 'keyword'},
 {'id': 'variety', 'name': 'variety', 'type': 'keyword'},
 {'id': 'arrival_date', 'name': 'arrival_date', 'type': 'date'},
 {'id': 'min_price', 'name': 'min_price', 'type': 'double'},
 {'id': 'max_price', 'name': 'max_price', 'type': 'double'},
 {'id': 'modal_price', 'name': 'modal_price', 'type': 'double'}]

In [37]:
df = pd.DataFrame(data_gen_info)
df

             id          name     type
0         state         state  keyword
1      district      district  keyword
2        market        market  keyword
3     commodity     commodity  keyword
4       variety       variety  keyword
5  arrival_date  arrival_date     date
6     min_price     min_price   double
7     max_price     max_price   double
8   modal_price   modal_price   double

In [30]:
data_extract = json.loads(data)
data_veg = data_extract["records"]
data_veg

[{'state': 'Maharashtra',
  'district': 'Mumbai',
  'market': 'Mumbai',
  'commodity': 'Sabu Dan',
  'variety': 'Other',
  'arrival_date': '2020-01-01T02:57:25Z',
  'min_price': 5600,
  'max_price': 6000,
  'modal_price': 5800},
 {'state': 'Maharashtra',
  'district': 'Mumbai',
  'market': 'Mumbai',
  'commodity': 'Sabu Dan',
  'variety': 'Other',
  'arrival_date': '2020-01-03T02:57:25Z',
  'min_price': 5600,
  'max_price': 6000,
  'modal_price': 5800},
 {'state': 'Maharashtra',
  'district': 'Mumbai',
  'market': 'Mumbai',
  'commodity': 'Sabu Dan',
  'variety': 'Other',
  'arrival_date': '2020-01-04T02:57:25Z',
  'min_price': 5600,
  'max_price': 6000,
  'modal_price': 5800},
 {'state': 'Maharashtra',
  'district': 'Mumbai',
  'market': 'Mumbai',
  'commodity': 'Sabu Dan',
  'variety': 'Other',
  'arrival_date': '2020-01-06T02:57:25Z',
  'min_price': 5600,
  'max_price': 6000,
  'modal_price': 5800},
 {'state': 'Maharashtra',
  'district': 'Mumbai',
  'market': 'Mumbai',
  'commodity': 'Sabu Dan',
  'variety': 'Other',
  'arrival_date': '2020-01-07T02:57:25Z',
  'min_price': 5600,
  'max_price': 6000,
  'modal_price': 5800},
 {'state': 'Maharashtra',
  'district': 'Mumbai',
  'market': 'Mumbai',
  'commodity': 'Sabu Dan',
  'variety': 'Other',
  'arrival_date': '2020-01-08T02:57:25Z',
  'min_price': 5600,
  'max_price': 6000,
  'modal_price': 5800},
 {'state': 'Maharashtra',
  'district': 'Mumbai',
  'market': 'Mumbai',
  'commodity': 'Sabu Dan',
  'variety': 'Other',
  'arrival_date': '2020-01-09T02:57:25Z',
  'min_price': 5500,
  'max_price': 5800,
  'modal_price': 5600},
 {'state': 'Maharashtra',
  'district': 'Mumbai',
  'market': 'Mumbai',
  'commodity': 'Sabu Dan',
  'variety': 'Other',
  'arrival_date': '2020-01-10T02:57:25Z',
  'min_price': 5500,
  'max_price': 5800,
  'modal_price': 5600},
 {'state': 'Maharashtra',
  'district': 'Mumbai',
  'market': 'Mumbai',
  'commodity': 'Sabu Dan',
  'variety': 'Other',
  'arrival_date': '2020-01-11T02:57:25Z',
  'min_price': 5500,
  'max_price': 5800,
  'modal_price': 5600},
 {'state': 'Maharashtra',
  'district': 'Mumbai',
  'market': 'Mumbai',
  'commodity': 'Sabu Dan',
  'variety': 'Other',
  'arrival_date': '2020-01-13T02:57:25Z',
  'min_price': 5500,
  'max_price': 5800,
  'modal_price': 5600}]

In [38]:
df = pd.DataFrame(data_veg)
df

,state,district,market,commodity,variety,arrival_date,min_price,max_price,modal_price
0,Maharashtra,Mumbai,Mumbai,Sabu Dan,Other,2020-01-01T02:57:25Z,5600,6000,5800
1,Maharashtra,Mumbai,Mumbai,Sabu Dan,Other,2020-01-03T02:57:25Z,5600,6000,5800
2,Maharashtra,Mumbai,Mumbai,Sabu Dan,Other,2020-01-04T02:57:25Z,5600,6000,5800
3,Maharashtra,Mumbai,Mumbai,Sabu Dan,Other,2020-01-06T02:57:25Z,5600,6000,5800
4,Maharashtra,Mumbai,Mumbai,Sabu Dan,Other,2020-01-07T02:57:25Z,5600,6000,5800
5,Maharashtra,Mumbai,Mumbai,Sabu Dan,Other,2020-01-08T02:57:25Z,5600,6000,5800
6,Maharashtra,Mumbai,Mumbai,Sabu Dan,Other,2020-01-09T02:57:25Z,5500,5800,5600
7,Maharashtra,Mumbai,Mumbai,Sabu Dan,Other,2020-01-10T02:57:25Z,5500,5800,5600
8,Maharashtra,Mumbai,Mumbai,Sabu Dan,Other,2020-01-11T02:57:25Z,5500,5800,5600
9,Maharashtra,Mumbai,Mumbai,Sabu Dan,Other,2020-01-13T02:57:25Z,5500,5800,5600